import { Inter } from "next/font/google";
import "./globals.css";
import NavbarActionButton from "@/components/shared/Navbar";
import FooterPrimaryDarkTheme from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Car Doctor Pro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <NavbarActionButton/>
        {children}
        <FooterPrimaryDarkTheme/>
        </body>
    </html>
  );
}
